# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            QAestro
tagline:          'QAestro'
description:      'Ontology-based Orchestration of Question Answering Pipelines'
baseurl:          https://wdaqua.github.io/QAestro/

github:
  repo:           https://github.com/WDAqua/QAestro
